module.exports = {
  docsSidebar: [
    'home',
    'repository-index',
    {
      type: 'category',
      label: 'Bit language',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'spec/bit' }]
    },
    {
      type: 'category',
      label: 'BIR',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'spec/bir' }]
    },
    {
      type: 'category',
      label: 'Boundaries',
      items: [
        { type: 'autogenerated', dirName: 'spec/abi' },
        { type: 'autogenerated', dirName: 'spec/runtime' },
        { type: 'autogenerated', dirName: 'spec/bootstrap' }
      ]
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }]
    },
    {
      type: 'category',
      label: 'Design',
      items: [{ type: 'autogenerated', dirName: 'design' }]
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }]
    },
    {
      type: 'category',
      label: 'RFCs',
      items: [{ type: 'autogenerated', dirName: 'rfcs' }]
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        { type: 'autogenerated', dirName: 'glossary' },
        { type: 'autogenerated', dirName: 'decisions' },
        { type: 'autogenerated', dirName: 'conformance' },
        { type: 'autogenerated', dirName: 'history' }
      ]
    }
  ]
};
